trigger:
  - none  # Set to manual trigger

pool:
  name: Default

stages:
  - stage: dev
    jobs:
      - job : deploy
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '1.5.0' 
          
         
