# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
 name: Default

variables:
  # Specify the Terraform version to use
  TF_VERSION: '1.5.0'
  TF_WORKING_DIR: './terraform'  # Path where the Terraform files are located
  # Azure environment variables (using Azure DevOps secrets for secure handling)
  ARM_SUBSCRIPTION_ID: "76589609-f356-45d6-9343-cacd37492e24"
  ARM_TENANT_ID: "8cb5854b-a2fc-4e63-86e8-692a9c16832a"

stages:
  - stage: 'Dev_Env'
    displayName: 'Deploy Infrastructure using Terraform into Dev Env'
    jobs:
      - job: 'Terraform'
        displayName: 'Terraform Init, Plan and Apply to Dev'
        steps:

          # Step 1: Install Terraform
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: $(TF_VERSION)
          
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'devserviceprncipal'
              backendAzureRmResourceGroupName: 'mrcloudrg'
              backendAzureRmStorageAccountName: 'mrcloudstg'
              backendAzureRmContainerName: 'mrcloudcontainer'
              backendAzureRmKey: 'terraform.tfstate'
              
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'devserviceprncipal'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'devserviceprncipal'
  - stage: 'Tst_Env'
    displayName: 'Deploy Infrastructure using Terraform into Tst Env'
    dependsOn: Dev_Env
    condition: succeeded()
    jobs:
      - job: 'Terraform'
        displayName: 'Terraform Init, Plan and Apply to Tst'
        steps:

          # Step 1: Install Terraform
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: $(TF_VERSION)
          
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Subscription 1(08e9cbbc-a29e-488d-8477-b22ab74e9325)'
              backendAzureRmResourceGroupName: 'mrcloudrg'
              backendAzureRmStorageAccountName: 'mrcloudstgtst'
              backendAzureRmContainerName: 'mrcloudcontainertst'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Subscription 1(08e9cbbc-a29e-488d-8477-b22ab74e9325)'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Subscription 1(08e9cbbc-a29e-488d-8477-b22ab74e9325)'