# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 name: Default

variables:
  # Specify the Terraform version to use
  TF_VERSION: '1.5.0'
  TF_WORKING_DIR: './terraform'  # Path where the Terraform files are located
  # Azure environment variables (using Azure DevOps secrets for secure handling)
  ARM_SUBSCRIPTION_ID: "76589609-f356-45d6-9343-cacd37492e24"
  ARM_TENANT_ID: "8cb5854b-a2fc-4e63-86e8-692a9c16832a"

stages:
  - stage: 'TerraformDeployment'
    displayName: 'Deploy Infrastructure using Terraform'
    jobs:
      - job: 'Terraform'
        displayName: 'Terraform Init, Plan and Apply'
        steps:

          # Step 1: Install Terraform
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: $(TF_VERSION)
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Azure subscription 1(76589609-f356-45d6-9343-cacd37492e24)'
          