# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

stages:
  - stage: dev
    jobs:
      - job : deploy
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '1.5.0' 
          
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure subscription 1(76589609-f356-45d6-9343-cacd37492e24)'
              backendAzureRmResourceGroupName: 'mrcloudrg'
              backendAzureRmStorageAccountName: 'mrcloudstg'
              backendAzureRmContainerName: 'mrcloudcontainer'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Azure subscription 1(76589609-f356-45d6-9343-cacd37492e24)'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Azure subscription 1(76589609-f356-45d6-9343-cacd37492e24)'

