trigger:
  - none  # Set to manual trigger

pool:
  name: Default

jobs:
- job: InstallTerraform
  steps:
  - script: |
      echo "Installing Terraform..."
     
    displayName: 'Install Terraform'
          
         
